// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEmail():Promise<string>;

export function IsLogged():Promise<boolean>;

export function LaunchTerminal(arg1:string):Promise<void>;

export function Login(arg1:string,arg2:number,arg3:boolean):Promise<number>;

export function Sync():Promise<string>;
