// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEmail() {
  return window['go']['main']['App']['GetEmail']();
}

export function IsLogged() {
  return window['go']['main']['App']['IsLogged']();
}

export function LaunchTerminal(arg1) {
  return window['go']['main']['App']['LaunchTerminal'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Sync() {
  return window['go']['main']['App']['Sync']();
}
